### PR TITLE
Ports cool TG lobby menu

### PR DESCRIPTION
**Pull request by SuperSlayer0**
## About The Pull Request

Replaces the ugly blue html lobby menu buttons with cool TG not ugly lobby menu buttons

Original PR: https://github.com/tgstation/tgstation/pull/60953

## Why It's Good For The Game

Looks better

## Changelog
:cl: Kryson, AMonkeyThatCodes, ported by SuperSlayer
imageadd: Replaces the lobby menu with sprites instead of HTML
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
tgstation at it again with the award winning undeniably good design 😏

**Comment by Pugie** [comment]
> tgstation at it again with the award winning undeniably good design 😏

Hi

**Comment by rdragan** [comment]
Looks like ass, has a vague state button, doesn't move. I was very happy to see the old html menu when we first got the server up.

**Comment by SuperSlayer0** [comment]
> Looks like ass, has a vague state button, doesn't move. I was very happy to see the old html menu when we first got the server up.

Lol

**Comment by TheChosenEvilOne** [comment]
I honestly prefer the old HTML UI.

**Comment by SweptWasTaken** [comment]
I loathe how the new menu looks and functions and it appears most of the other contributors do so i'm just going to close it.

**Pull request closed without merging**
