### PR TITLE
Makes job clothing vendors free for jobs from same department.

### PR DESCRIPTION
**Pull request by TheChosenEvilOne**
## About The Pull Request
You will no longer have to pay for the drip.

## Why It's Good For The Game
idk

## Changelog
:cl:
add: clothing in clothing vendors is now free for jobs, except for premium clothing.
/:cl:

### CODE REVIEW

**Comment by AcapitalA** [comment]
Good PR, you shouldn't have to pay for basic gear just to properly do your job.

**Comment by JinGiant** [comment]
I really thought this was already in the game.

**Comment by TheChosenEvilOne** [comment]
> I really thought this was already in the game.

it was changed by tgeeeee

**Comment by Pugie** [comment]
> Good PR, you shouldn't have to pay for basic gear just to properly do your job.

If you think you need drip to do your job sure 🤓

**Comment by Burgermancoding** [comment]
> > Good PR, you shouldn't have to pay for basic gear just to properly do your job.
> 
> If you think you need drip to do your job sure 🤓

Drip or drown Pugie

**Comment by Pugie** [comment]
It's true it, dept clothes costing cash just meant people wouldn't buy premiumware clothes because they were too expensive and needed to buy other stuff.

**Review by EdgeLordExe — APPROVED** [review]
LGTM

**Pull request merged**
