### PR TITLE
esword airlock slicing

### PR DESCRIPTION
**Pull request by TheChosenEvilOne**
## About The Pull Request
Allows slicing open airlocks with esword.

## Why It's Good For The Game
https://www.youtube.com/watch?v=K48M2S7bkSA

## Changelog
:cl:
add: Added slicing airlocks open with energy swords.
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
I think 10 seconds a little too fast, but the idea is cool

**Comment by TheChosenEvilOne** [comment]
> I think 10 seconds a little too fast, but the idea is cool

That is on desword which has a force of 34, it takes nine hits from it to break an airlock. melee attack cooldown is 8 deciseconds, so it takes 7,2 seconds to break an airlock by just hitting it.

**Comment by TheChosenEvilOne** [comment]
now that I actually think about it, it should actually be faster on both.

**Comment by Livrah** [comment]
Does it have a sound durning do_after? Breaking an airlock by esword hits is loud af.

**Comment by TheChosenEvilOne** [comment]
> Does it have a sound durning do_after? Breaking an airlock by esword hits is loud af.

there is a sound when you start it and a sound when it ends.

**Pull request merged**
