### PR TITLE
Bloodsuckers

### PR DESCRIPTION
**Pull request by SuperSlayer0**
## About The Pull Request

Yes i am porting two new antags in a one week gap. 

It is a port of a port of a port that ports [my merchant port](https://github.com/The-Merchants-Guild/Merchant-Station-13/pull/330) of [yogstation port](https://github.com/yogstation13/Yogstation/pull/13273) of fulp bloodsuckers yeah. 

Bloodsuckers are a cool vampire themed antag with many mechanics like level progression, conversion, day and night cycles and etc. They are just cool.

Check this for more info: https://wiki.fulp.gg/en/Bloodsucker

image

## Why It's Good For The Game

Bloodsuckers are cool also this adds more variety to the game

## Changelog
:cl: TheSwain, JohnFulpWillard, SuperSlayer
rscadd: Added new antags from fulp: bloodsuckers and monster hunters, together with stakes and other structures and a new language
soundadd: added new epic bloodsucker and monster hunter sounds (together with many owls)
imageadd: added new books and coffins
spellcheck: fixed some minor coding spelling mistakes
/:cl:

### CODE REVIEW

**Comment by SuperSlayer0** [comment]
I think it is ready for something like a testmerge

**Comment by SuperSlayer0** [comment]
Remove merge conflict label

**Comment by SuperSlayer0** [comment]
Will test it with friends at friday

**Comment by SuperSlayer0** [comment]
From the test on my local server it works and doesn't have any game breaking bugs

**Comment by SuperSlayer0** [comment]
Cool erp in atmospherics
image

**Comment by EdgeLordExe** [comment]
Doesn't fit our server

**Comment by SuperSlayer0** [comment]
Sad

**Pull request closed without merging**
