### PR TITLE
Bring back cocoa felinid interaction and change chocolate drink recipes

### PR DESCRIPTION
**Pull request by PolishUser**
## About The Pull Request

This PR will add the felinid cocoa interaction and change chocolate milk, hot chocolate recipes.

## Why It's Good For The Game
More flavour for the felinid race.
## Changelog
:cl:
add: When felinids get chocolate reagents they get disgust and slight internal organ damage (brain, eyes, liver, heart)
balance: Changed chocolate milk and hot chocolate recipes.
/:cl:

### CODE REVIEW

**Comment by Pugie** [comment]
https://i.imgur.com/YXdgz0T.png

**Comment by JinGiant** [comment]
cats can have a little chocolate

**Comment by EdgeLordExe** [comment]
hi oranges

**Pull request merged**
