### PR TITLE
The Big Wound Removal

### PR DESCRIPTION
**Pull request by TheChosenEvilOne**
## About The Pull Request
Removes wounds and all code related to them. have fun reviewing this.

## Why It's Good For The Game
Requested + wounds very RNG and just ass in general.

## Changelog
:cl:
del: Wounds have been removed from code.
del: Due to wound removal scars have also been removed.
tweak: Wound related heretic abilities now use bleeding.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
lol

**Comment by AcapitalA** [comment]
TCEO doing gigantic things per usual, actual madman.

**Comment by Pugie** [comment]
Cool

**Comment by TotallyNotChief** [comment]
Based. Now revert fusion to the previous version without the HFR.

**Pull request merged**
