### PR TITLE
Re-adds yellow slime core recharge function

### PR DESCRIPTION
**Pull request by HansRobertCoooding**
## About The Pull Request

 hopefully reverts tgstation/tgstation/pull/54198.

## Why It's Good For The Game
 Reverts a stupid nerf.

## Changelog
:cl:
add: Recharging yellow extract power cells
/:cl:

### CODE REVIEW

**Comment by SuperSlayer0** [comment]
Good change

**Comment by Pugie** [comment]
Good change

**Comment by AcapitalA** [comment]
Interdepartmental interaction done right. Gives people some powerful gear if they're actually willing to talk to xenobiologists and rewards interaction in general. 👍

**Comment by SuperSlayer0** [comment]
Meet the self recharging stunbaton

**Pull request merged**
