### PR TITLE
Ports TG living heart

### PR DESCRIPTION
**Pull request by SuperSlayer0**
## About The Pull Request

Ports TG no metagame living heart. I would prefer to also port the codex citatrics part but I don't think that I am competent enough for that. Also replaces gibbing on heretic sacrificing(because it is effectively removing a person from the round) by spilling their organs out and dealing 250 damage.

HOPE THAT THIS WILL WORK

## Why It's Good For The Game

Less ways to metagame heretics

## Changelog
:cl: Melbert, SuperSlayer
add: Heretic living heart is now one of their organs
add: Replaces gibbing on heretic sacrificing with heavily damaging and spilling organs out
/:cl:

### CODE REVIEW

**Comment by EdgeLordExe** [comment]
port the book changes aswell

**Comment by SuperSlayer0** [comment]
> port the book changes aswell

It will require some fucking with TGUI, and my knowledge in TGUI equals to zero. Perhaps someone else can port the codex citatrics part, but not me.

**Comment by Burgermancoding** [comment]
I prefer the person being permanently round removed

**Comment by SuperSlayer0** [comment]
> I prefer the person being permanently round removed

Ok then have fun sitting in ghosts 1-2 hours after being sacrificed by a heretic

**Comment by Burgermancoding** [comment]
> > I prefer the person being permanently round removed
> 
> Ok then have fun sitting in ghosts 1-2 hours after being sacrificed by a heretic

Our rounds dont last for 2 hours, being caught by a heretic should be punishing. If they want to log off until next round or for later or to never come back they can, dying should be punishing. If it is babified in this way there is less paranoia overall in the game and it is not good. We want people to be afraid to go into dark places where bad people lay in wait, we want people to be wary of their co-workers. We don't want things that are going to appease the ided waah people, even if it just spills their organs they will get spaced or their brain will be destroyed anyway.

**Comment by SuperSlayer0** [comment]
Lol, it doesn't make it not punishing to die. It just makes it not round removing, because you still can be revived(but it isn't guaranteed, since the heretic can hide or space your body or just it can be not found). Other antagonists such as traitors or changelings do not fucking gib you when they kill you, so I don't see any reason why heretics should.

**Comment by Livrah** [comment]
Not gibbing AND spilling organs out is a good buff for heretics, since they need bodies for ghouls/rituals.

**Comment by SuperSlayer0** [comment]
Will be tested at the weekend

**Comment by SuperSlayer0** [comment]
Tested, doesn't work 👍

**Comment by SuperSlayer0** [comment]
Just doesn't work, close this

**Pull request closed without merging**
