### PR TITLE
Un-removes standard cyborg module

### PR DESCRIPTION
**Pull request by SuperSlayer0**
## About The Pull Request

It, as it says, un-removes the standard cyborg module(don't be cofused with returns, because will it be in the game is not a thing that i decide). It adds a config option similar to peacekeeper borgs and secborgs to enable/disable standard cyborg module. Enabled by default, unless you will uncoment it.

## Why It's Good For The Game

Reverts a stupid TG removal that nobody asked for

## Changelog
:cl: SuperSlayer
add: Standard cyborg module
add: A config option to disable/enable standard cyborg module
/:cl:

### CODE REVIEW

**Comment by Sparkezel** [comment]
imo it was removed for a good reason, its very much a validhunting borg with cablecuffs

**Comment by SuperSlayer0** [comment]
> imo it was removed for a good reason, its very much a validhunting borg with cablecuffs

There is a config option for an even more validhunting secborg, so it should be okay.

**Comment by Sparkezel** [comment]
well then if it has a config thats better

**Comment by SuperSlayer0** [comment]
Also even if a borg has strong validhunting tools it is still a skill issue such any competent antagonist or even a normal crewmember can easily counter it(flashes? EMPs? glasses?)

**Comment by SuperSlayer0** [comment]
Fuuuuck

**Comment by SuperSlayer0** [comment]
Tested this, will revive later
image
Ingame borg screenshot, save here for revive PR

**Pull request closed without merging**
