### PR TITLE
Restores bag of holding to former glory but without boh bombing.

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Removes the inert version of the bag of holding, lets you produce full bags from the lathes as before. Removes the boh bomb singulo, this is now just a fancy backpack (like it always should have been).

## Why It's Good For The Game
Another goal for the gamers to achieve.

## Changelog
:cl:
balance: Bag of holding no longer requires an anomaly core to build, inert version removed. You can no longer boh bomb (very effectively).
/:cl:

### CODE REVIEW

**Comment by EdgeLordExe** [comment]
was the hilbert ruin changed back? they removed the BoH from there for whatever reason

**Comment by AcapitalA** [comment]
> no longer BoH bomb
AAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by kriskog** [comment]
> was the hilbert ruin changed back? they removed the BoH from there for whatever reason

Ill put it back

> > no longer BoH bomb
> 
> AAAAAAAAAAAAAAAAAAAAAAAAA

maybe something else... stay posted.


Also I need to clean up maps, sigh.

**Comment by Pugie** [comment]
good, anomaly sci is dumb

**Comment by kriskog** [comment]
> maybe something else... stay posted.
> 

Thought about this, came to my senses. For now, this is done.

**Comment by EdgeLordExe** [comment]
doing this just for testing

**Pull request merged**
