### PR TITLE
Blob now has xray and can see/hear ghosts

### PR DESCRIPTION
**Pull request by SuperSlayer0**
## About The Pull Request

Allows ghosts to bully the blob for playing bad and not making blobernauts for them to play as

## Why It's Good For The Game

You can now bully the blob as a ghost

## Changelog
:cl:
add: Makes blob have xray vision and allows it to see/talk to/hear ghost
/:cl:

### CODE REVIEW

**Comment by AcapitalA** [comment]
"whoa i wonder if they're gonna print the beam rifles in time"
"they're going to the southern exposed part with emitters"
"here comes sec with nothing but shotguns"

You DO realize you're basically giving the blob a T O N of extra information right?

**Comment by SuperSlayer0** [comment]
> "whoa i wonder if they're gonna print the beam rifles in time" "they're going to the southern exposed part with emitters" "here comes sec with nothing but shotguns"
> 
> You DO realize you're basically giving the blob a T O N of extra information right?

Blob is a camera mob that can fly everywhere where it wants and see almost anything, so it can see it all alone. This just allows ghosts to do something like teaching newbies or asking the blob to make some blobernauts to play as.

**Comment by kriskog** [comment]
lmao no

**Comment by Burgermancoding** [comment]
This is a good pr. I will tell you why, simply put most people do not understand how to play blob, pulling up a wiki on the fly guarantees loss or death and is cancer. The best way to learn is from other players who will help you in dead chat. having the extra information is a non-issue since you can just see it yourself anyway

**Comment by Burgermancoding** [comment]
Also even with the extra information you'll get steamrolled anyway since maybe like 3 people ever win as blobs consistently or ever

**Comment by rdragan** [comment]
lol

**Pull request closed without merging**
