### PR TITLE
Makes biting food instant again.

### PR DESCRIPTION
**Pull request by AcapitalA**
## About The Pull Request
This PR brings back the old way of eating food.

## Why It's Good For The Game
Nobody likes to stand around, waiting for their little guy to eat something, seemingly incapable of moving legs while doing so.

## Changelog
:cl:
qol: Biting food is now instant again!
/:cl:

### CODE REVIEW

**Comment by SuperSlayer0** [comment]
Sex

**Comment by AcapitalA** [comment]
Sex

**Comment by Sparkezel** [comment]
fix your title, you are just able to eat and move not instantly consume

**Comment by AcapitalA** [comment]
You instantly take a bite rather, like how it was before.

**Pull request merged**
