### PR TITLE
Makes engineering hardsuit immune to radiation

### PR DESCRIPTION
**Pull request by Sparkezel**
## About The Pull Request

increases engi hardsuit rad resistance from 75% to 100%

## Why It's Good For The Game

Its essentially quality of life, you cant really do any good SM memes without rad protection and space protection or being a plasmeme

## Changelog
:cl:

balance: Engineering hardsuit now has full rad protection

/:cl:

### CODE REVIEW

**Comment by AcapitalA** [comment]
Me walking around medbay in an engisuit with 6 nuclear reactors taped to a ripley named CANCER-TRON-6000.

This is gonna be interesting...

**Review by Canohaaaaaaa — APPROVED** [review]

**Comment by Pugie** [comment]
Kind of against this, it's what values the CE hardsuit. If you delam sm and you don't have the suit you're gonna have to either prioritise protection against pressure (hardsuit) or against rads (radsuit) and that makes it harder to save sm. It also makes it more important for would be delammers to kill CE.

**Comment by KangTut** [comment]
I agree with Pugie. You can still do SM setups with only the rad suit but anything that needs to be done inside the chamber can be done before you turn it on. It generates rads after it has been activated and if you are trying to delam it there are still ways to do it with only a rad suit.

**Comment by Canohaaaaaaa** [comment]
Would rather we get a proper look at every hardsuit in a single PR or possibly a MODsuit port.

**Pull request closed without merging**
