### PR TITLE
Sec borg rework

### PR DESCRIPTION
**Pull request by SuperSlayer0**
## About The Pull Request

Makes security borgs less cancer and more balanced

Ports many yog pr's:
https://github.com/yogstation13/Yogstation/pull/6865
https://github.com/yogstation13/Yogstation/pull/7563
https://github.com/yogstation13/Yogstation/pull/7588
https://github.com/yogstation13/Yogstation/pull/11596

Gives secborgs a donut dispenser, makes their guns self recharging rather then being infinity laser spam thingie, makes security borg locked behind advanced weaponry research(**_still can be disabled/enabled through config_**) and security borg module picker upgrade and disalows people jobbaned from security to play as a sexurity borg. 

## Why It's Good For The Game

Allows silicon players to have FUN(validhunting is fun). It isn't a really strong crew buff because you can subvert secborgs as any other borgs, they are still bound by laws and are easily counterable even by stealth antagonists(emp kit my beloved), so this, while allowing borgs to pick a validhunting module doesn't make them a really strong enemy because they are still more weak then a human security member since they are hardstunned by EMP's and flashes(flashes are very easily to get and borgs can only cry about that) and also are, again, bound by laws. 

## Changelog
:cl: ynot01, Ktlwjec1, alexkar598, JamieD1, ported by SuperSlayer
add: Security cyborgs now have a donut synthesizer.
balance: Security module cyborgs now have an auto-charging disabler instead of one that draws from their cell
del: Removed the ability to chose the security module on borgs by default.
add: Added an upgrade to allow a borg to switch to the security module. It is locked behing the Advanced Weaponry tech node
add: People jobbaned from sec no longer can become a secborg
/:cl:

### CODE REVIEW

**Comment by SuperSlayer0** [comment]
Edit: It doesn't enable the borg is config because i found out that in the code it is already enabled so idk

**Comment by AcapitalA** [comment]
Gave me a heart attack until i read the advanced weaponry bit. Still not sure how to feel about this honestly.

**Comment by SuperSlayer0** [comment]
It still requires config enabling to be able to use the module so it should be okay.

**Comment by SuperSlayer0** [comment]
Will be tested tomorow with many other my PR's

**Comment by SuperSlayer0** [comment]
Tested localy, should work
image

**Pull request closed without merging**
