### PR TITLE
[MDB IGNORE] Reverts smart pipes + adds pipe mapping helper.

### PR DESCRIPTION
**Pull request by TheChosenEvilOne**
## About The Pull Request
Reverts smart pipes and adds a pipe mapping helper to help lazy mappers.

## Why It's Good For The Game
Smart pipes are awful

## Changelog
:cl:
del: Smart pipes have been removed and replaced with old simple pipes.
/:cl:

### CODE REVIEW

**Comment by TheChosenEvilOne** [comment]
Mapping changes all done, here are the regexes I used to replace typepaths in the maps:
```
\/obj\/machinery\/atmospherics\/pipe\/smart\/(?:manifold4w|simple|manifold)(.*?)(?:\{\n\s*?dir = [\d]+\s*?\}|(?=,))
\/obj\/machinery\/atmospherics\/pipe\/smart\/(?:manifold4w|simple|manifold)(.*)(?=\{)
\/obj\/machinery\/atmospherics\/pipe\/bridge_pipe(.*?)(?:\{\n\s*?dir = [\d]+\s*?\}|(?=,))
(?<=layer_manifold)(?:/.*)(/.*)(?=,|\{)
(?<=layer_manifold)/hidden
```

**Comment by Sparkezel** [comment]
somethings up with pumps, they cannot fully dump their contents into output pipenet causing problems with precise bomb making in toxins

**Comment by TheChosenEvilOne** [comment]
> somethings up with pumps, they cannot fully dump their contents into output pipenet causing problems with precise bomb making in toxins

this shouldn't be an issue with this PR, pumps are not touched here at all.

**Comment by Sonnicon** [comment]
> somethings up with pumps, they cannot fully dump their contents into output pipenet causing problems with precise bomb making in toxins

Normal behaviour, your output has 2 pipenets. The pipe itself, and the output buffer of the pump. Unwrench the pump if you need more precision, or adjust your volume and pressure.

**Comment by Addust** [comment]
Smart pipes are good. You are not.

**Pull request merged**
