### PR TITLE
Updates nanite anti-stuns.

### PR DESCRIPTION
**Pull request by AcapitalA**
## About The Pull Request
This PR updates the nanite anti-stun program to work off stamina rather than hard stuns, updating it back into relevancy.
It now has 50% reduced impact of stamina damage on top of it's current effect.

## Why It's Good For The Game
More old stuff brought back into relevancy, what's not to love?

## Changelog
:cl:
balance: Updates the Nerve Support nanite program to also work with stamina.
/:cl:

### CODE REVIEW

**Comment by Pugie** [comment]
Good

**Comment by Pugie** [comment]
It's probably worth keeping the stun resistance too so it keeps relevance vs cults and xenos

**Comment by AcapitalA** [comment]
Fair, but i'm not sure if 50% hardstun resist on top is too powerful. Eh, whatever.

**Comment by Pugie** [comment]
shouldn't be too powerful, whole idea is to help against stuns so might as well help against both as opposed to just one.

**Pull request merged**
