### PR TITLE
Wounds rework

### PR DESCRIPTION
**Pull request by Canohaaaaaaa**
### Goal
Shift wounds into a punishment for falling into crit/dying. This will prevent them from happening mid-combat by *most* common damage sources.

Instead wounds now have two states : **active** and **inactive**
When wounded while fighting a wound first starts as **inactive** and has *no effect*, however if the owner falls into crit/dies all of their wounds turn into **active** ones. This state is kept even if they are revived or brought out of crit.
There are 2 exceptions :
-  **Delimbs** are applied instantly, would be even more jarring otherwise.
- **Slash wounds**, they only inflict bleeds. Had this not been done it would be impossible to bleed without first going into crit which is meh. They have however been toned down accordingly from 4.25/3.25/2 to 3.25/2.5/1.5 bloodloss (critical/severe/moderate).

The only way to heal inactive wounds is through cryo or simply time (changelings can also instantly heal them).
It takes 3 minutes per severity for an inactive wound to heal, up to a maximum of 9 minutes for critical wounds.
This should force you to go to medbay and not impact solo-antags since they are expected NOT TO LOSE fights.

**Wound bonus** no longer exists as a combat stat on weapons, thus wounds strictly depend on how much damage was taken and cannot be snowflaked away most of the time. A strong weapon will mess you up and this cannot be changed by anything beside your armor, which has kept its wound armor rating.
This means that when designing a weapon no thought should be given to wounds, as they will just be results of how brutal your weapon is.
However you can make armor more resilient to wounds, this will not make them any better at direct combat since everything is buffered but delimbs and bleeds, it will however make it much less punishing to go into crit while wearing heavy armor.

## Changelog
:cl: Nitrome
balance: Wounds have been reworked, all wounds beside bleeds (slash) and delimbs are now punishments for falling into critical condition rather than mid-combat status effects.
balance: Wounds now have 2 states, active and inactive, inactive wounds have no effect until critical condition is reached, they fade away over time.
balance: Slash wounds bloodloss reduced from 4.25/3.25/2 -> 3.25/2.5/1.5.
/:cl:

### CODE REVIEW

**Comment by Rowelll** [comment]
I teared up while reading this

**Comment by Canohaaaaaaa** [comment]
Inactive wounds now seal up with time, unless you get a worse wound of the same type on the exact same limb. In which case the timer is increased and reset.

**Comment by Canohaaaaaaa** [comment]
Alright, I would like this be playtested to gather feedback.
I would like to know if you're getting **too many** wounds and if they had any impact while you were brawling, note that getting more wounds overall is intended, I just want to know if it was completely ridiculous or not.

**Comment by Canohaaaaaaa** [comment]
Sucks

**Pull request closed without merging**
