### PR TITLE
re adds printable slugs and buck plus minor balance change

### PR DESCRIPTION
**Pull request by manofpepsi**
## About The Pull Request

you can now print slugs and buckshot like in the good old days and also slightly buffs riot shotgun's firing speed and makes the pulse slug deal 40 damage (also re adds the lethals locker if you want to map it)

## Why It's Good For The Game

the slugs and buckshot have been tweaked a bit to be less powerfull also pulse slugs were nerfed despite not even being good 

## Changelog
:cl: Pepsiman
add: good shotgun ammo is printable again
add: pulse slugs deal 40 damage 
/:cl:

### CODE REVIEW

**Comment by Pugie** [comment]
brave

**Comment by AcapitalA** [comment]
I'll map em in once it's merged. Just @ me.

**Comment by SuperSlayer0** [comment]
Cool sec can now again oneshot you with a shotgun in melee

**Comment by Naloacisamazing** [comment]
Slugs.... >:(

**Comment by Burgermancoding** [comment]
> Cool sec can now again oneshot you with a shotgun in melee

Already can

**Comment by Canohaaaaaaa** [comment]
Didn't put the shotgun or pulse buff in the changelog and also why did you buff shotguns overalkl while adding back the most powerful ammo for it.

**Review by Canohaaaaaaa — CHANGES_REQUESTED** [review]
Didn't put the shotgun or pulse buff in the changelog and also why did you buff shotguns overall while adding back the most powerful ammo for it.

**Pull request merged**
